### ISSUE TITLE
The "raw response" is not logged correctly

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/steps-bitrise-ios-deploy#2]
Related line (there are actually two): https://github.com/bitrise-io/steps-bitrise-ios-deploy/blob/76d121fe1db54f873e3fa01b042a7d58b7a5b73f/bitrise_build_uploader.rb#L122

It prints the raw response _object_ but not it's content - which means that it doesn't really print anything in the logs.

**Comment by godrei** [comment]
This step is deprecated please use `deploy-to-bitrise-io` step instead of this.
